### ISSUE TITLE
Bluetooth / VKB focus issue

### ISSUE THREAD

**Issue by imso** [RyanHope/wTerm#21]
Bluetooth keyboard seems to be working great with wterm (incl. Caps Lock).
But if a key on the VKB is pressed, bluetooth keys won't be processed until
the terminal area is tapped.

**Comment by imso** [comment]
Fixed in 0.3.1.

**Comment by Garfonso** [comment]
I have the very same issue with the hardware keyboard of my Pre3 in 0.4.0. Is this a regression or is this caused by sonething else on the phone? Should I open a new issue for that?
