### ISSUE TITLE
htop rendering error

### ISSUE THREAD

**Issue by dtzWill** [RyanHope/wTerm#23]
When running color htop, the top line gets erased and doesn't render properly.

htop installed from ipkg-opt.

This only happens when TERM=xterm (htop runs in color mode); TERM=vt100 results in a uncolored but textually complete htop.

**Comment by RyanHope** [comment]
In vtterminalstate.cpp:77

case CS_ECH: //ESC[<Line>X
    erase(Point(m_cursorLoc.getX(), m_cursorLoc.getY()), Point(m_cursorLoc.getX()+values[0], m_cursorLoc.getY()));
    break;

This is the offending line of code, this escape sequence should erase characters.

**Comment by dtzWill** [comment]
Fixed in bd80e6cedd57057ebdf974936fce98decb2c394f and 6e30c8823305f7c88ab485e4cd41baebf419ebb9.
