### ISSUE TITLE
Bluetooth keyboard - esc and arrow keys

### ISSUE THREAD

**Issue by JinbaIttai** [RyanHope/wTerm#29]
As mentioned in #21 - Bluetooth keyboards mostly work - but the arrow keys don't do anything
Tested on HP wireless keyboard and Freedom Pro keyboard.

The ESC key on the Freedom Pro doesn't work either

Is there an easy way to see what scancodes are being received?

**Comment by RyanHope** [comment]
Fixed in 0.3.2

**Comment by JinbaIttai** [comment]
Thanks for the update!  
Arrow keys now work on both keyboards, but ESC on the Freedom pro brings up my "notifications" (ie right now it tells me about the 3.0.5 "update available"
On the HP keyboard there is no ESC key, but the top-left key is used for exactly that - notifications - so it is possible it really sends the ESC scancode and webOS catches that and uses it internally.

**Comment by RyanHope** [comment]
Yes that is exactly what is happening. Ctrl+[ should also send ESC but it also brings up notifications. Brybry is working on a workaround for this. I suppose we can make a custom keybindings for escape using other key combinations.
