### ISSUE TITLE
doesn't run on my phone, touchpad only

### ISSUE THREAD

**Issue by dtzWill** [RyanHope/wTerm#30]
It'd be great to have wterm avail on the phone platforms too.  How to manage things like the vkb (replace full kbd with mini keyboard for control/esc/arrows/etc?) would need some work, but otherwise should "port" fairly easily.

**Comment by RyanHope** [comment]
So wTerm already has visual lock identifies for shift alt and crtl. I replaced fn with sym, so I should prob bright that back for phones. A mini strip of keys for arrows and other needed keys could be an optional feature also.
