### ISSUE TITLE
cursor disappears in vi/mcedit

### ISSUE THREAD

**Issue by dtzWill** [RyanHope/wTerm#32]
cursor often doesn't show up in vi or in mcedit.

(via http://forums.webosnation.com/webos-internals/309714-wterm-webos-terminal-emulator-2.html#post3280072, but confirmed on my build)

See Puff's comment below for more detailed description of the issue.

**Comment by RyanHope** [comment]
to be more specific, the vi the cursor disappears when you enter insert mode, in vim I did not experience this behavior, the cursor was always visible. NOTE my TERM is set to xterm. I have not tried mcedit yet. Also note there is an escape code that controls cursor visibility , maybe it's not getting reset or something.

**Comment by dtzWill** [comment]
I did not mean to add 'vim', I did not test it and as you point out it does not to seem to suffer from this issue.  Good catch, and my apologies.  Also tested with TERM=xterm.
