### ISSUE TITLE
Full support of Midnight commander

### ISSUE THREAD

**Issue by mrothtrc** [RyanHope/wTerm#7]
Hi,

cool app ! Thanks for your work
it would be great if you could support mc with all vkb key bindings.

Testcase:
ipkg-opt install mc
mc
no colors no fkeys ESC-0 works
export TERM=xterm
mc -a
looks better but no keybindings ESC-9 opens menu

sent from my TP

**Comment by RyanHope** [comment]
Thanks, I was looking for more heavy escape code apps to test this out with. I will add it to my test bed and get it as fully supported as possible.

**Comment by RyanHope** [comment]
What keybindings still dont work in mc? All the function keys work for me as does color and box drawing characters.

**Comment by RyanHope** [comment]
I am marking this as complete. Let me know if there are still issues.
