### ISSUE TITLE
No build/developer instructions

### ISSUE THREAD

**Issue by dtzWill** [RyanHope/wTerm#72]
**We** know how to build it, but a short guide that describes the setup would be useful.

Beyond build.git usage (the officially supported method), light documentation for BUILD_ROOT, DEVICE, and LOGLEVEL would be useful for new developers :).

I'm happy to tackle this when I get some time, but just wanted to track it as a known issue :).

**Comment by RyanHope** [comment]
https://github.com/PuffTheMagic/wTerm/wiki/Building
