### ISSUE TITLE
vim scroll up doesn't work

### ISSUE THREAD

**Issue by dtzWill** [RyanHope/wTerm#79]
This used to work, at least on some commit I was playing with, so shouldn't be too far off.

Anyway, the bug can be seen if you use vim on a file that goes beyond the screen vertically.  Scroll down, and then try scrolling back up.  When scrolling up it appears we don't scroll at all (don't move the existing lines down I mean), and so instead just continually overwrite the top line.

Probably shows up in other applications too :).

**Comment by RyanHope** [comment]
What is your TERM when this happens?

**Comment by dtzWill** [comment]
It's 'xterm'.  Same happens with rxvt.  Setting to vt100 results in different behavior: When scrolling up, instead of not scrolling the screen it seems to scroll it 2x as much, resulting in blank lines between the text in vim.

**Comment by dtzWill** [comment]
Looks like ea1ffa0d2933144faeefa152878151d106279dba fixed this.

There are other (very) minor things wrong, but I'll file separate issues for those as needed; the major bug, and the one mentioned in this issue, is now fixed!

(Hooray I can use vim again :D)
