### ISSUE TITLE
No resize of full keyboard on touchpad

### ISSUE THREAD

**Issue by maybeec** [RyanHope/wTerm#93]
Today I have found the wTerm 0.4 release in preware, I have been waiting for so long. Thanks for this great App!
Unfortunately the keyboard does not fully resize all keys when rotating the touchpad to landscape format.

**Comment by RyanHope** [comment]
Someone else reported a similar issue. Toggling the rotation lock fixed it for him. Would you please try and and see if that fixed the problem.

**Comment by maybeec** [comment]
Yes, nice.. now everything is working. Also after I have restarted the app or the whole device, the problem seems to be fixed. Misterious ;)
Thanks!
