### ISSUE TITLE
Some control keys don't work from Bluetooth keyboard

### ISSUE THREAD

**Issue by bmastenbrook** [RyanHope/wTerm#95]
I'm having an issue typing Control-A and Control-[ from my Bluetooth keyboard. All other useful control key combinations seem to work fine in my testing. I'm able to type these keys from the soft keyboard correctly. Control-A from the Bluetooth keyboard also works as expected in other parts of the OS.

I'm testing with 0.4.0-2 from Preware on webOS 3.0.5. The keyboard is a Think Outside Stowaway that I've been using with various devices for years.

**Comment by RyanHope** [comment]
Thats cause webos eats those events, there is nothing we can do about it. I submitted a bug upstream one of the webOS devs I talk fairly regularly requesting app level control of such keybindings and he said he would put it on their todo list. I have no idea when that will get implemented though. For now, you have to deal with this.

**Comment by bmastenbrook** [comment]
Thanks for the response! I didn't see it listed as a known issue anywhere, so I wasn't sure if it was just a bug.
